#!/bin/bash
echo "<a href="$1/$2.pdf">$2</a>"
echo "<ol>"
if grep -q 'olimport\[' $1/$2.tex ; then
    for f in `grep 'olimport' $1/$2.tex | grep -v '\.\.' | sed "s/^.*\olimport\[\([^]]*\)\]{\([^}]*\)}/\1\/\2/"` ; do
	echo "<li>"
    d="$(dirname $f)"
    ff="$(basename $f)"
	$0 $1/$d $ff
	echo "</li>"
   done
   fi
if grep -q 'olimport{' $1/$2.tex ; then
    for f in `grep 'olimport' $1/$2.tex | grep -v '\.\.' | sed "s/^.*\olimport{\([^}]*\)}/\1/"` ; do
	echo "<li><a href="$1/$f.pdf">$f</a></li>"
   done
   fi
echo "</ol>"
